// Generated by CoffeeScript 1.6.3
(function() {
  var value;

  value = null;

  module.exports.get = function() {
    return value;
  };

  module.exports.set = function(newValue) {
    return value = newValue;
  };

}).call(this);
