// Generated by CoffeeScript 1.6.3
console.log(__dirname, 'LOADING');
var value;
module.exports.get = function() {
  return value;
};

module.exports.set = function(newValue) {
  return value = newValue;
};
